WATERBIRDS_NAME = 'waterbirds'
CELEBA_NAME = 'celebA'
PACS_NAME = 'pacs'
CXR_NAME = 'cxr'
VLCS_NAME = 'vlcs'

IMAGE_DATA=[WATERBIRDS_NAME,CELEBA_NAME,CMNIST_NAME,FMOW_NAME,
            IMAGENETS_NAME,PACS_NAME,SD_CATDOG_NAME,CXR_NAME,
            SD_NURSE_FIREFIGHTER_NAME,BREEDS17_NAME,BREEDS26_NAME, VLCS_NAME]
WILDS_DATASETS = [WATERBIRDS_NAME,CELEBA_NAME]

CIVILCOMMENTS_NAME = 'civilcomments'
HATEXPLAIN_NAME = 'hatexplain'
AMAZON_NAME = 'amazon'
GENDER_BIAS_NAME = 'gender'
TEXT_DATA=[CIVILCOMMENTS_NAME, HATEXPLAIN_NAME, AMAZON_NAME, GENDER_BIAS_NAME]

T5_NAME = 'flan-t5'
GPT2_NAME = 'gpt2'
LLAMA_NAME = 'llama'
CHATGPT_NAME ='chatgpt'
SUPPORTED_LM = [T5_NAME, GPT2_NAME, LLAMA_NAME, CHATGPT_NAME]

CLIP_BASE_NAME = 'clip'
CLIP_BIOMED_NAME = 'clip_biomed'
CLIP_ALIGN_NAME = 'align'
CLIP_ALT_NAME = 'alt'
CLIP_OPEN_VITL14 = 'openclip_vitl14'
CLIP_OPEN_VITB32 = 'openclip_vitb32'
CLIP_OPEN_VITH14 = 'openclip_vith14'
CLIP_OPEN_RN50 = 'openclip_rn50'

SUPPORTED_CLIP = [CLIP_BASE_NAME, CLIP_BIOMED_NAME, CLIP_ALIGN_NAME, CLIP_ALT_NAME, CLIP_OPEN_VITL14, 
                  CLIP_OPEN_VITB32, CLIP_OPEN_VITH14, CLIP_OPEN_RN50]

HF_CLIP = [CLIP_BASE_NAME, CLIP_ALIGN_NAME, CLIP_ALT_NAME]
OPEN_CLIP = [CLIP_BIOMED_NAME, CLIP_OPEN_VITL14, CLIP_OPEN_VITB32, CLIP_OPEN_VITH14, CLIP_OPEN_RN50]
