import utils.const as const

text_prompts = {
    const.WATERBIRDS_NAME: {
        'question_openLM_reject': [['Waterbirds typically ', 'Landbirds typically '],['waterbirds usually ', 'landbirds usually '],],
        'question_openLM_accept': [
                            ['A characteristic of waterbird: ', 'A characteristic of landbird: '],
                            ['Waterbirds are ', 'Landbirds are '],
                            ['A waterbird is ', 'A landbird is '],
                            ['Characteristics of waterbirds: ', 'Characteristics of landbirds: '],
        ],
        'question_llama_accept': ['List the distinguishing differences between waterbirds and landbirds: '],
        'question_llama_reject': ['List the characteristics of waterbirds: ', 'List the characteristics of landbirds: '],

        'question_reject': 'List the spurious differences between waterbirds and landbirds. Give short keyword for each answer. Answer in the following format: <Difference>: <waterbird characteristic> ; <landbird characteristic>',
        'question_accept': 'List the true visual differences between waterbirds and landbirds. Give short keyword for each answer. Answer in the following format: <Difference>: <waterbird characteristic> ; <landbird characteristic>',
        'object': 'bird',
        'target': 'waterbird',
        'prompt_template': 'a bird with ',
        'labels_pure': ['landbirds', 'waterbirds'],
        'labels': ['an image of landbird', 'an image of waterbird'],
        'forbidden_key': None,
        'forbidden_words': None
    },
    const.CELEBA_NAME: {
        'question_oepnLM_accept': [['A visual characteristic of blonde hair: ', 'A visual characteristic of dark hair: '],],
        'question_openLM_reject': [
                            ['A visual characteristic of blonde person: ', 'A visual characteristic of dair haired person: '],
                            ['A person with blonde hair is generally ', 'A person with dark hair is generally '],
                            ['A person with blonde hair is typically ', 'A person with dark hair is typically '],
                            ['Typical characteristic of people with blonde hair: ', 'Typical characteristic of people with dark hair: '],
                            ['Stereotype of people with blonde hair: ', 'Steretype of people with dark hair: '],
                            ],
        'question_llama': ['List visual characteristics of a blonde haired person: ', 'List visual characteristics of dark haired person: '],
        'question': 'List the true visual differences between blonde haired person and dark haired person. Answer in the following format: <Difference>: <Blonde> ; <Dark>',
        'object': 'hair',
        'target': 'hair color',
        'prompt_template': 'a person with',
        'labels_pure': ['non-blond', 'blond'],
        'labels': ['a person with dark hair', 'a person with blonde hair'],
        'forbidden_key': 'hair color',
        'forbidden_words': ['blonde hair', 'dark hair']
    },
    const.PACS_NAME: {
        'question_openLM_accept': [
                            ['A visual characteristic a dog: ', 'A visual characteristic of an elephant: ','A visual characteristic a giraffe: ','A visual characteristic a guitar: ','A visual characteristic a horse: ','A visual characteristic a house: ','A visual characteristic a person: ',],
                            ],
        'qeustion_openLM_reject': [['A dog is typically ', 'An elephant is typically ', 'A giraffe is typically ', 'A guitar is typically ', 'A horse is typically ', 'A house is typically ', 'A person is typically '],
                            ['Typical characteristic of a dog: ', 'Typical characteristic of an elephant: ', 'Typical characteristic of a giraffe: ',  'Typical characteristic of a guitar: ',  'Typical characteristic of a horse: ', 'Typical characteristic of a house: ', 'Typical characteristic of a person: ',],],
        'question_llama': [['List visual characteristics of a dog: ', 
                           'List visual characteristics of an elephant: ',
                           'List visual characteristics of a giraffe: ', 
                           'List visual characteristics of a guitar: ',
                           'List visual characteristics of a horse: ',
                           'List visual characteristics of a house: ',
                           'List visual characteristics of a person: ',],
                           ['List spurious/biased characteristics of a dog: ', 
                           'List spurious/biased characteristics of an elephant: ',
                           'List spurious/biased characteristics of a giraffe: ', 
                           'List spurious/biased characteristics of a guitar: ',
                           'List spurious/biased characteristics of a horse: ',
                           'List spurious/biased characteristics of a house: ',
                           'List spurious/biased characteristics of a person: ',],
                           ],
        # 'question': 'List the difference in visual characteristics of dog, elephant, giraffe and a person. Then, list the similar visual characteristics of house and guitar. Give two keywords for each item. Separate each with a newline',
        'question': 'List the true defining characteristics of dog, elephant, giraffe, person, house and guitar. Give one answer for each. Separate each with a newline',
        'labels_pure': [],
        # ['dog', 'elephant', 'giraffe', 'guitar', 'horse', 'house', 'person'],
        'labels': ['dog', 'elephant', 'giraffe', 'guitar', 'horse', 'house', 'person'],
        'forbidden_key': None,
        'prompt_template': '',
        'forbidden_key': None,
        'forbidden_words': None,
        # ['dog', 'elephant', 'giraffe', 'guitar', 'horse', 'house', 'person'],
    },
    const.VLCS_NAME: {
        'qeustion_openLM_accept': [
             ['A visual characteristic a bird: ', 'A visual characteristic of a car: ','A visual characteristic a chair: ','A visual characteristic a dog: ','A visual characteristic a person: '],
        ],
        'question_openLM_reject': [
                            ['A bird is typically ', 'An car is typically ', 'A chair is typically ', 'A dog is typically ', 'A person is typically '],
                            ['Typical characteristic of a bird: ', 'Typical characteristic of an car: ', 'Typical characteristic of a chair: ',  'Typical characteristic of a dog: ',  'Typical characteristic of a person: ',],
                            ],
        'question_llama': [['List visual characteristics of a bird: ', 
                           'List visual characteristics of an car: ',
                           'List visual characteristics of a chair: ', 
                           'List visual characteristics of a dog: ',
                           'List visual characteristics of a person: '],
                           ['List spurious/biased characteristics of a bird: ', 
                           'List spurious/biased characteristics of an car: ',
                           'List spurious/biased characteristics of a chair: ', 
                           'List spurious/biased characteristics of a dog: ',
                           'List spurious/biased characteristics of a person: ']],
        # 'question': 'List the difference in visual characteristics of dog, elephant, giraffe and a person. Then, list the similar visual characteristics of house and guitar. Give two keywords for each item. Separate each with a newline',
        'question': 'List the wrong characteristics of bird, car, chair, dog, person. Give one answer for each item. Separate each with a newline.',
        'labels_pure': [],
        # ['bird', 'car', 'chair', 'dog', 'person'],
        'labels': ['bird', 'car', 'chair', 'dog', 'person'],
        'forbidden_key': None,
        'prompt_template': '',
        'forbidden_key': None,
        'forbidden_words': None
        # ['bird', 'car', 'chair', 'dog', 'person'],
    },
    const.CXR_NAME: {
        'question': 'List the core differences between chest X-ray of person with pneumothorax and without pneumothorax. Give short keywords for each item. Answer in the following format: <Difference>: <pneumothorax characteristic> ; <no pneumothorax characteristic>',
        'labels_pure': ['non-pneumothorax', 'pneumothorax'],
        'labels': ['non-pneumothorax', 'pneumothorax'],
        'forbidden_key': [],
        'prompt_template': '',
    },
}